name: Project reminders

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  schedule-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Perform Check
        run: ./gradlew run
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          USERNAME: ${{ secrets.MAVEN_PKG_USERNAME }}
          TOKEN: ${{ secrets.MAVEN_PKG_PASSWORD }}

